server:
  port: 8081

spring:
  application:
    name: backend-service
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO

# Cấu hình giới hạn dung lượng file upload